services:
  - type: web
    name: django-ci-cd-demo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py runserver 0.0.0.0:10000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
